---
- ros_topic_name: "/manipulator/joint_1/position_cmd"
  gz_topic_name: "/model/manipulator/joint_1/position"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/manipulator/joint_2/position_cmd"
  gz_topic_name: "/model/manipulator/joint_2/position"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/manipulator/joint_states"
  gz_topic_name: "/world/demo/model/manipulator/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS

